---
- name: Install Nginx
  hosts: all
  become: true
  tasks:
    - name: update cache
      apt:
        update_cache: yes
    - name: Install Nginx package
      apt:
        name: nginx
        state: present
    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
