name: Install Nginx
 
on:
  workflow_dispatch:
 
jobs:
  install_nginx:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          # inventory: inventory.ini,
          # playbook: nginxinstall.yml

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
      - name: Set up Ansible
        uses: garygrossgarten/github-action-ansible@v1
        with:
          playbook: nginxinstall.yml
          inventory: inventory.ini
 
      # - name: Update apt Package and Install Ansible
      #   run: |
      #     sudo apt update
      #     sudo apt install ansible
      #     # python -m pip install --upgrade pip
      #     # pip install ansible

      - name: check directory
        run: |
          ls
          ansible all -i inventory.ini -m ping
          

      
         
 
      # - name: Set up Private SSH key
      #   run: |
      #     mkdir -p /home/runner/.ssh
      #     echo "${{ secrets.PRIVATE_SSH_KEY }}" > /home/runner/.ssh/id_rsa
      #     chmod 400 /home/runner/.ssh/id_rsa
 
      # - name: Ping Node
      #   run: |
      #     ansible all -i inventory.ini -m ping
 
      # - name: Run Ansible playbook
      #   run: |
      #     ansible-playbook -i inventory.ini nginx-install.yml
