name: Deploy Nginx on EC2

on:
  workflow_dispatch:
    inputs:
      Run it:
        description: 'Wanna run'
        required: true
        
jobs:
  deploy-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install pip
        run: python -m ensurepip --default-pip

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          sudo pip3 install ansible

      - name: Clear Known Hosts File
        run: rm -f ~/.ssh/known_hosts
        
      - name: Set up SSH Key
        run: |
          mkdir -p /home/runner/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 400 /home/runner/.ssh/id_rsa
        shell: bash

      - name: Display SSH Key
        run: cat ~/.ssh/id_rsa


      - name: Add EC2 Host Key
        run: ssh-keyscan -H -t rsa 13.127.204.111 >> ~/.ssh/known_hosts
  
      - name: Display SSH Key and Known Hosts
        run: |
          cat ~/.ssh/id_rsa
          cat ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.ini --private-key=/home/runner/.ssh/id_rsa -u ubuntu -b nginxinstall.yml







# name: Install Nginx

# on:
#   workflow_dispatch:

# jobs:
#   install_nginx:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.x'

#       # - name: Set up SSH
#       #   uses: webfactory/ssh-agent@v0.5.3
#       #   with:
#       #     ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}

#       - name: Install pipx
#         run: |
#            sudo apt update
#            sudo apt install -y ansible
#           # python -m pip install --upgrade pip
#           # pip install --user pipx

#       # - name: Install Ansible with pipx
#       #   run: |
#       #     pipx install --include-deps ansible

#       - name: Check directory
#         run: |
#           ls
#           pwd
#           echo "${{secrets.SSH_PRIVATE_KEY}}" > mainfile.pem
#           chmod 600 mainfile.pem
#           ansible all -i inventory.ini -m ping --private-key=<(echo "${{ secrets.SSH_PRIVATE_KEY }}") --user=ubuntu
#         env:
#           SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
















# name: Install Nginx
 
# on:
#   workflow_dispatch:
 
# jobs:
#   install_nginx:
#     runs-on: ubuntu-latest
 
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
 
#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.x'
#           # inventory: inventory.ini,
#           # playbook: nginxinstall.yml

#       - name: Set up SSH
#         uses: webfactory/ssh-agent@v0.5.3
#         with:
#           ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
#       - name: Set up Ansible
#         run: |
#          sudo apt update
#          sudo apt install pipx
#          pipx ensurepath
#          pipx install --include-deps ansible
 
#       # - name: Update apt Package and Install Ansible
#       #   run: |
#       #     sudo apt update
#       #     sudo apt install ansible
#       #     # python -m pip install --upgrade pip
#       #     # pip install ansible

#       - name: check directory
#         run: |
#           ls
#           pwd
#           echo "${{secrets.SSH_PRIVATE_KEY}}" > mainfile.pem
#           chmod 400 mainfile.pem
#           ansible all -i inventory.ini -m ping
          

      
         
 
      # - name: Set up Private SSH key
      #   run: |
      #     mkdir -p /home/runner/.ssh
      #     echo "${{ secrets.PRIVATE_SSH_KEY }}" > /home/runner/.ssh/id_rsa
      #     chmod 400 /home/runner/.ssh/id_rsa
 
      # - name: Ping Node
      #   run: |
      #     ansible all -i inventory.ini -m ping
 
      # - name: Run Ansible playbook
      #   run: |
      #     ansible-playbook -i inventory.ini nginx-install.yml
